// All user-facing text lives here (English only). Components reference keys and never carry
// their own wording. Text that depends on a value is a small function.
//
// `d` is always the name of the person's device: "iPhone" or "iPad" once chosen, and
// "iPhone or iPad" before that.

const CERT_NAME = "authexodus (remove after use)";
const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const en = {
  appName: "authexodus",
  certName: CERT_NAME,

  deviceName: { iphone: "iPhone", ipad: "iPad", either: "iPhone or iPad" },

  common: {
    loading: "Starting…",
    havingTrouble: "Having trouble?",
    close: "Close",
    tryAgain: "Try again",
    done: "Done",
    previous: "Previous",
    next: "Next",
    pictureOf: (n: number, total: number) => `Picture ${n} of ${total}`,
    showPicture: "Show picture",
    hidePicture: "Hide picture",
    showPictureFor: (label: string) => `Show picture for: ${label}`,
    hidePictureFor: (label: string) => `Hide picture for: ${label}`,
    stepOf: (n: number, total: number, name: string) => `Step ${n} of ${total}: ${name}`,
    stopAndCleanUp: "Stop and clean up",
    keepGoing: "Keep going",
    restart: "Restart the connection",
    restarting: "Restarting…",
    restartFailed: "The connection could not be restarted. Try again.",
    authyFinish: "Finish signing in to Authy: enter your backup password there so it keeps working as your fallback. If you cannot find the password, your codes can only be reached from another device where Authy is still signed in.",
    loadFailed: "The app could not start.",
  },

  rail: {
    label: "Steps",
    steps: {
      welcome: "Safety check",
      connect: "Connect",
      certificate: "Certificate",
      authy: "Reinstall Authy",
      unlock: "Unlock",
      destination: "Move codes",
      verify: "Check codes",
      cleanup: "Clean up",
    },
    finished: "finished",
    version: (v: string) => `Version ${v}`,
    releases: "New versions are published at",
  },

  welcome: {
    title: "Move your codes out of Authy",
    lede: "This app copies your two-step login codes from Authy into another authenticator app. It takes about 20 minutes. Your codes stay on this computer unless you choose to send them to Bitwarden.",
    network: "Only do this on a home or office network you control. Do not use public or shared Wi-Fi.",
    planTitle: "What you will do",
    plan: [
      "Connect your iPhone or iPad to this computer for a few minutes.",
      "Delete Authy and install it again. This app catches the locked copy of your codes as Authy signs in.",
      "Unlock them here with your Authy backup password and move them to your new app.",
      "Put the iPhone or iPad back the way it was.",
    ],
    deviceQuestion: "Which device has Authy on it?",
    android: "Android phone",
    spare: "Safest: use a spare iPad or iPhone if you have one. Your everyday phone then keeps working the whole time. Install Authy on it and sign in first, then choose it above.",
    androidTitle: "This app can't help with an Android phone",
    androidBody: "Getting codes out of Authy on Android needs changes to the phone that most people should not make. If you can borrow an iPhone or iPad, install Authy on it, sign in, and choose it above. Otherwise, move each account by hand.",
    checksTitle: "Check five things before you start",
    checksWhy: "You are going to delete Authy and install it again. Without these five, you could be locked out for 24 hours or lose codes.",
    checks: {
      device: {
        label: (d: string) => `Authy on this ${d} shows my codes`,
        where: "Open Authy and check that your accounts are listed.",
      },
      backups: {
        label: "Backups are turned on in Authy",
        where: "In Authy, open Settings and look for Authenticator Backups (usually under Accounts). It should be switched on.",
      },
      password: {
        label: "I know my Authy backup password",
        where: "The password Authy asks for on a new device. It is not the passcode that unlocks the screen. If you are not sure of it, stop: once Authy is deleted, your codes cannot be opened without it.",
      },
      multiDevice: {
        label: "Multi-device is turned on in Authy",
        where: "In Authy, open Settings and look for Allow Multi-device (usually under Devices). It should be switched on.",
      },
      sms: {
        label: "I can get a text message on the phone number my Authy account uses",
        where: "Authy sends a code by text when you sign in again. If that number is old or the phone is not with you, stop.",
      },
    },
    start: "Start",
    blocked: "Choose your device and tick all five to start.",
    blockedChecks: (n: number) => `${plural(n, "check", "checks")} left to tick.`,
    footer: "authexodus is not affiliated with Twilio or Bitwarden. It exports your own data.",
  },

  connect: {
    title: (d: string) => `Connect your ${d} to this computer`,
    lede: (d: string) => `For the next few minutes your ${d} sends its internet traffic through this computer. iOS calls this a proxy. Only Authy's traffic is read. Everything else passes straight through. Keep this window open until the end.`,
    starting: "Getting this computer ready…",
    startFailed: (d: string) => `This computer could not start listening for your ${d}.`,
    server: "Server",
    port: "Port",
    valuesLabel: (d: string) => `Type these on your ${d}`,
    addressLabel: "This computer's address",
    addressHint: (d: string) => `If your ${d} can't connect, try the other address.`,
    addressOption: (ip: string, label: string) => `${ip} (${label})`,
    addressRejected: (ip: string) => `The address can't change to ${ip} without restarting the connection.`,
    addressChanged: (d: string) => `This computer's address has changed. Update Server and Port on your ${d} to the ones shown here.`,
    restartOn: (ip: string) => `Restart on ${ip}`,
    steps: {
      wifi: { iphone: "Open Settings and tap Wi-Fi.", ipad: "Open Settings and tap Wi-Fi in the sidebar." },
      info: "Tap the blue ⓘ beside the network you are connected to.",
      configure: "Scroll down and tap Configure Proxy.",
      manual: (ip: string, port: number) => `Tap Manual. Type ${ip} for Server and ${port} for Port. Leave Authentication off.`,
      save: "Tap Save.",
    },
    firewall: "If your Mac asks whether to allow incoming connections, choose Allow.",
    waiting: (d: string) => `Waiting for your ${d} to connect. This screen moves on by itself.`,
  },

  certificate: {
    title: "Install the certificate",
    lede: "The app uses this certificate only to read what Authy sends. You remove it at the end.",
    fingerprintLabel: "Certificate fingerprint (SHA-256)",
    fingerprintHow: (d: string) => `Before you switch on trust, open the profile on your ${d}, tap More Details, then the certificate, and compare its SHA-256 fingerprint with this one. If they differ, do not trust it: choose Having trouble?, then Stop and clean up.`,
    connected: (d: string) => `Your ${d} is connected.`,
    qrAlt: "QR code that opens the certificate download page",
    orType: "Or type this address into Safari:",
    steps: {
      scan: (d: string) => `Point the ${d}'s Camera at the code and open the link.`,
      download: "Tap Download certificate, then Allow.",
      profile: "Open Settings and tap Profile Downloaded near the top. If it is not there, go to General → VPN & Device Management.",
      install: "Tap Install, enter your passcode, and tap Install again.",
      trust: (d: string) => `The step people miss: go to Settings → General → About → Certificate Trust Settings and switch on the profile named ${CERT_NAME}, or the one with authexodus in its name. Your ${d} shows a warning. That is expected. Tap Continue.`,
      test: "Go back to the page from the first step and tap Test.",
    },
    waiting: "Waiting for the certificate to be trusted. This screen moves on by itself.",
  },

  authy: {
    title: "Delete Authy, then install it again",
    lede: "Authy has no sign-out, so this is the way to make it fetch your codes again. As long as those hold, your codes stay safe in Authy's backup.",
    lastCheck: {
      title: "You are about to delete Authy",
      body: "You confirmed: backups are on, you know the backup password, multi-device is on, and you can get a text on your Authy number. Not sure of one? Choose Having trouble?, then Stop and clean up.",
    },
    trusted: "The certificate is trusted.",
    steps: {
      remove: (d: string) => `Delete the Authy app from your ${d}: touch and hold its icon, then choose the option to remove it and confirm you want to delete the app.`,
      install: "Install Authy again from the App Store and open it.",
      phone: "Enter your phone number and choose SMS to verify.",
      stop: "Stop when Authy asks for your backup password, and come back here.",
    },
    waiting: "Waiting for Authy to fetch your codes. This screen moves on by itself.",
  },

  unlock: {
    captured: (n: number) => `Captured ${plural(n, "account", "accounts")}`,
    title: "Unlock your codes",
    lede: "Type your Authy backup password. It is used only on this computer, exactly as you type it, and is never saved.",
    label: "Authy backup password",
    show: "Show password",
    submit: "Unlock",
    working: "Unlocking…",
    alsoAuthy: (d: string) => `When this works, type the same password into Authy on your ${d} too. Authy then keeps working as a fallback.`,
    forgotten: "Can't find the password? Keep trying here: nothing is lost by a wrong try. If Authy is still signed in on another device, move each account by hand from that one.",
    failed: "The codes could not be unlocked. Try again.",
  },

  destination: {
    title: "Where should your codes go?",
    lede: (n: number) => `${plural(n, "account is", "accounts are")} ready to move. Pick one way. You can come back and use another.`,
    none: "No accounts could be unlocked for moving.",
    authyTitle: "First, finish signing in to Authy",
    authyBody: (d: string) => `On your ${d}, enter your backup password in Authy so it keeps working as your fallback.`,
    continueBlocked: "Check the codes is switched off until something has been moved: scan a QR code and tick it, save a file, or finish the Bitwarden step.",
    options: {
      qr: { title: "Scan into any app", body: "One QR code per account. Works with every authenticator app." },
      bitwarden: { title: "Bitwarden, matched to your logins", body: "Adds each code to the login it belongs to. You review every match first." },
      google: { title: "Google Authenticator", body: "A few QR codes that each carry up to 10 accounts." },
      file: { title: "Save a file for another app", body: "1Password, 2FAS, Aegis, Proton Authenticator, Bitwarden, or plain text." },
    },
    usedTag: "used",
    continue: "Check the codes",
    cantMoveTitle: (n: number) => `${plural(n, "account", "accounts")} can't be moved`,
    cantMoveLede: "These stay in Authy until you set them up again yourself.",
    native: (name: string) => `${name} uses Authy's own 7-digit codes. Sign in to ${name}, open its security settings, and set up two-step login again with your new app.`,
    invalid: (name: string) => `${name} is not a usable authenticator key. Set up two-step login again in that account's security settings.`,
    backToOptions: "Back to the choices",

    qr: {
      title: "Scan each code with your new app",
      lede: "In your new app, choose to add an account by scanning a QR code. Scan this one, tick it, then go to the next.",
      scanned: "I scanned this code into my new app",
      scannedCount: (n: number, total: number) => `${n} of ${total} scanned`,
      position: (n: number, total: number) => `Account ${n} of ${total}`,
      alt: (name: string) => `QR code for ${name}`,
      loading: "Drawing the code…",
      warning: "Anyone who photographs these codes can copy your accounts. Keep the screen to yourself.",
      failed: "The code could not be drawn. Go back to the choices and try again.",
    },
    google: {
      title: "Scan into Google Authenticator",
      lede: "In Google Authenticator, open the menu and look for Transfer accounts, then Import accounts, and scan each code. Tick each one as you go.",
      position: (n: number, total: number) => `Code ${n} of ${total}`,
      alt: (n: number) => `Google Authenticator transfer code ${n}`,
      unsupportedTitle: (n: number) => `${plural(n, "account is", "accounts are")} not in these codes`,
      unsupportedBody: "Google's transfer codes can't carry every kind of account. Add what is listed here with “Scan into any app” instead.",
    },
    file: {
      title: "Save a file for another app",
      lede: "Pick your app, save the file, then use that app's import option to open it.",
      warning: "The file holds the keys to your accounts with no lock on it. Import it, then delete it and empty the Trash.",
      save: (app: string) => `Save a file for ${app}`,
      saved: (path: string) => `Saved to ${path}`,
      cancelled: "Nothing was saved.",
      failed: "The file could not be saved. Try again.",
      apps: {
        onePassword: "1Password",
        twoFas: "2FAS",
        aegis: "Aegis",
        protonAuthenticator: "Proton Authenticator",
        bitwarden: "Bitwarden",
        plainText: "Plain text",
      },
    },
  },

  bitwarden: {
    introTitle: "Add your codes to Bitwarden",
    introBody: "To talk to Bitwarden, this app downloads Bitwarden's own command-line tool and checks that it is genuine. Apart from this download, the app only uses the internet when Bitwarden's tool talks to Bitwarden.",
    introNext: "After that you sign in, review every match, and only then is anything changed.",
    prepare: "Download and continue",
    preparing: "Downloading Bitwarden's tool and checking it…",
    prepareFailed: "The download did not work. Check this computer's internet connection and try again.",

    loginTitle: "Sign in to Bitwarden",
    loginLede: "This app passes your master password to Bitwarden's own official tool on this computer, and does not keep it.",
    twoStepLimit: "If Bitwarden asks for a two-step code, only codes from an authenticator app work here. If yours come by email or a security key, or Bitwarden emails you a code to confirm a new device, go back and choose Save a file for another app, then Bitwarden.",
    showPassword: "Show master password",
    passwordHeld: "Your master password is being held only until this sign-in finishes.",
    email: "Email address",
    password: "Master password",
    region: "Where is your Bitwarden account?",
    regions: { us: "bitwarden.com", eu: "bitwarden.eu", selfHosted: "My own server" },
    serverUrl: "Server address",
    serverUrlHint: "For example https://vault.example.com",
    serverUrlInvalid: "Enter the full address, starting with https://",
    twoFactor: "Two-step login code",
    needsTwoFactor: "Bitwarden needs your two-step login code. Enter the 6-digit code from your authenticator app and sign in again.",
    wrongTwoFactor: "Bitwarden did not accept that code. Wait for a new one and try again.",
    badCredentials: "Bitwarden did not accept that email and master password. Type both again.",
    loginFailed: "Signing in to Bitwarden did not work. Check this computer's internet connection and try again. If your account needs an emailed code or a security key, use Save a file for another app, then Bitwarden.",
    signIn: "Sign in",
    signingIn: "Signing in…",
    matching: "Reading your vault and matching accounts…",

    reviewTitle: "Review the matches",
    reviewLede: "Nothing has changed yet. We suggested a login for each account. Change any that are wrong. Accounts the app could not match become new entries in the “Authy import” folder, which you can merge in Bitwarden afterwards. Skipped accounts stay only in Authy. A code that is already in Bitwarden is never replaced.",
    colAccount: "Authy account",
    colAction: "What to do in Bitwarden",
    question: "Which Bitwarden login does this code belong to?",
    questionHasCode: "The matching login already has a code. What should happen?",
    choose: "Choose…",
    attach: (name: string, username: string | null) => (username ? `Add to ${name} (${username})` : `Add to ${name}`),
    attachHasCode: (name: string, username: string | null) =>
      `${username ? `${name} (${username})` : name}: already has a code`,
    createNew: "Create a new login in the “Authy import” folder",
    skip: "Skip this account",
    actionFor: (title: string) => `What to do with ${title}`,
    needChoice: (n: number) => `${plural(n, "account needs", "accounts need")} your choice first.`,
    apply: "Apply to Bitwarden",
    applyingTitle: "Updating Bitwarden",
    applying: "Adding codes to Bitwarden…",
    progressLabel: "Progress",

    reportTitle: "Bitwarden is updated",
    reportPartialTitle: "Bitwarden is partly updated",
    attached: (n: number) => `Added a code to ${plural(n, "login", "logins")}.`,
    created: (n: number) => `Created ${plural(n, "new login", "new logins")} in the “Authy import” folder.`,
    skipped: (n: number) => `Skipped ${plural(n, "account", "accounts")}.`,
    kept: (names: string[]) => `Left alone because a code was already there: ${names.join(", ")}.`,
    runAgain: "Run again",
  },

  verify: {
    title: "Check the codes match",
    lede: "Open your new app and compare a few accounts with the codes below. They should be identical. Codes change every 30 seconds.",
    listLabel: "Current codes",
    secondsLeft: (n: number) => `${n}s`,
    secondsLeftLabel: (n: number) => `${plural(n, "second", "seconds")} left`,
    loading: "Working out the codes…",
    mismatch: "A code doesn't match? Check that the date and time are set automatically where your new app is installed, then compare again. Still different? Go back and move that account again. Do not clean up yet.",
    failed: "The codes could not be worked out. The app keeps trying.",
    cantMove: (n: number) => `${plural(n, "account is", "accounts are")} not in this list because ${n === 1 ? "it" : "they"} can't be moved. ${n === 1 ? "It still lives" : "They still live"} only in Authy.`,
    forget: "After this step the app forgets your codes.",
    confirm: "They match. Clean up",
    another: "Move them to another app too",
  },

  cleanup: {
    title: "Put everything back",
    noInternet: (d: string) => `Your ${d} has no internet until you switch its proxy off. Do that first.`,
    vpnBack: "If you switched off a VPN or iCloud Private Relay earlier, switch it back on now.",
    resumed: "The app was closed before clean-up finished last time. Finish these steps now.",
    working: "Stopping the connection and destroying the certificate's secret key…",
    clean: (d: string) => `This computer is clean: the connection is stopped and the certificate's secret key is destroyed, so the certificate on your ${d} is useless.`,
    failed: "This computer could not finish cleaning up.",
    failedReason: (reason: string) => `The reason given: ${reason}`,
    failedManual: "You can finish it by hand: open Keychain Access on this Mac, search for authexodus, and delete the item it finds. Carry on with the steps below either way.",
    manualDone: "I deleted the authexodus item in Keychain Access",
    deviceQuestion: "Which device did you use?",
    todo: (d: string) => `Now do these on your ${d}, and tick each one.`,
    items: {
      proxyOff: {
        label: "I turned the proxy off",
        how: "Settings → Wi-Fi → ⓘ beside your network → Configure Proxy → Off → Save.",
      },
      profileRemoved: {
        label: "I removed the certificate profile",
        how: `Settings → General → VPN & Device Management → the profile named ${CERT_NAME}, or the one with authexodus in its name → Remove Profile.`,
      },
      authySignedIn: {
        label: "Authy is signed in and shows my codes",
        how: "Finish signing in to Authy: enter your backup password there so it keeps working as your fallback. If you never deleted Authy, check that it still opens. If you cannot find the password, tick this once you know which other device still has Authy signed in.",
      },
      fileDeleted: {
        label: "I deleted the file I saved",
        how: "Import it into your new app first. Then delete it on this computer and empty the Trash.",
      },
      fileDeletedMaybe: {
        label: "I deleted any file I saved",
        how: "If you saved an import file before the app was closed, delete it on this computer and empty the Trash. If you saved none, tick this.",
      },
    },
    keepAuthy: "Keep Authy installed for a week or two. If a code in your new app ever fails, Authy is still there. Do not delete Authy until you have set up again every account this app listed as one it can't move.",
    remaining: (n: number) => `${plural(n, "item", "items")} left to tick.`,
    finish: "Finish",
  },

  done: {
    title: "All done",
    body: (d: string) => `Your ${d} and this computer are back to normal.`,
    titleNothingMoved: "Cleaned up. Nothing was moved",
    bodyNothingMoved: "Your codes are still in Authy. You can run authexodus again from the start, or move each account by hand.",
    keepAuthy: "Keep Authy installed for a week or two as a fallback. Do not delete Authy until you have set up again every account this app listed as one it can't move.",
    notMoved: (n: number) => `${plural(n, "account was", "accounts were")} not moved and still ${n === 1 ? "lives" : "live"} only in Authy: set ${n === 1 ? "it" : "them"} up again in each account's security settings.`,
    again: "To move your codes to another app later, run authexodus again from the start.",
    close: "You can close this window.",
  },

  manual: {
    title: "Move an account by hand",
    steps: [
      "Sign in to the account on its website.",
      "Open its security settings and find two-step login. It may be called two-factor or 2FA.",
      "Choose to set up the authenticator app again. Use the code from Authy if it asks for one.",
      "Scan the new QR code with your new app and type in the code it shows.",
      "Repeat for each account. Keep Authy until every one is moved.",
    ],
  },

  failures: {
    sheetTitle: "Having trouble?",
    sheetLede: "These are the usual causes. Open the one that sounds right.",
    restart: {
      title: "Restart the connection",
      body: (d: string) => `Use this if your ${d} joined a different Wi-Fi, its address changed, or nothing above helps. Your ${d} keeps its certificate: it only needs to reconnect, and Authy needs to be opened again. The next screens repeat. Do not redo them: check the Server and Port still match, open the Test page, then close Authy and open it again.`,
      noticeAfterTrust: (d: string) => `You restarted the connection. You already installed the certificate on your ${d}, and you may have deleted Authy. Do not do either again: check Server and Port still match, open the Test page, then close Authy and open it again.`,
      noticeBeforeTrust: (d: string) => `You restarted the connection. Skip any step you have already done on your ${d}: check Server and Port still match, then carry on from where you were.`,
      lost: "Anything captured so far is discarded.",
    },
    stop: {
      title: "Stop and clean up?",
      lost: (d: string) => `This throws away anything captured from Authy and destroys the certificate's secret key, so the certificate on your ${d} becomes useless. It cannot be undone.`,
      redo: "To try again later you start from the beginning: connect, install a new certificate, and reinstall Authy.",
    },
    deviceRefused: {
      title: "Authy can't connect? Another device was turned away",
      body: (d: string) => `This computer only listens to the first ${d} that connected. Another device, or your ${d} after its address changed, just tried to reach Authy and was refused.`,
      next: (d: string) => `If it was your ${d}, restart the connection. It keeps its certificate: it only needs to reconnect, and Authy needs to be opened again.`,
    },
    firewall: {
      title: "Your Mac may be blocking the connection",
      body: (d: string) => `When this app opened, your Mac may have asked whether authexodus can accept incoming network connections. If it was not allowed, your ${d} can't reach this computer.`,
      steps: [
        "Open System Settings and search for Firewall (usually under Network), then open its Options.",
        "Find authexodus in the list and set it to Allow incoming connections.",
        "Or quit authexodus, open it again, and choose Allow when asked.",
      ],
    },
    wifi: {
      title: "Both devices must be on the same Wi-Fi",
      body: (d: string) => `Your ${d} and this computer have to be on the same Wi-Fi network.`,
      steps: (d: string, ip: string, port: number) => [
        `On the ${d}, check that Settings → Wi-Fi shows the same network name as this computer.`,
        "Guest, hotel and café networks often stop devices talking to each other. Use your home network, not its guest network.",
        `Check that Server and Port on the ${d} match exactly: ${ip} and ${port}.`,
      ],
      stepsNoAddress: (d: string) => [
        `On the ${d}, check that Settings → Wi-Fi shows the same network name as this computer.`,
        "Guest, hotel and café networks often stop devices talking to each other. Use your home network, not its guest network.",
      ],
    },
    vpn: {
      title: (d: string) => `Turn off VPN and iCloud Private Relay on the ${d}`,
      body: "Both send traffic around this computer, so nothing arrives here.",
      steps: [
        "Private Relay: Settings → your name → iCloud → Private Relay → switch off.",
        "VPN: Settings → VPN → switch off.",
        "Switch them back on when you have finished.",
      ],
    },
    trust: {
      title: "The certificate isn't trusted yet",
      body: (d: string) => `That is expected until every step is done. Installing the certificate is not enough: your ${d} also needs trust switched on for it.`,
      steps: [
        "Open Settings → General → About.",
        "Scroll to the bottom and tap Certificate Trust Settings.",
        `Switch on the profile named ${CERT_NAME}, or the one with authexodus in its name, and tap Continue.`,
        "Not in the list? The profile isn't installed yet. Go to Settings → General → VPN & Device Management and install it first.",
      ],
    },
    attestation: {
      title: "Authy reported a problem",
      body: "Wait a minute, then try again in Authy.",
      ifAttestation: "If Authy mentions an “attestation token”, it is refusing to start while the proxy is on. Doing it in this order gets around it:",
      steps: (ip: string, port: number) => [
        "Turn the proxy off: Settings → Wi-Fi → ⓘ → Configure Proxy → Off → Save.",
        "Open Authy and enter your phone number.",
        `Before you choose SMS, turn the proxy back on: Manual, Server ${ip}, Port ${port}, Save.`,
        "Go back to Authy and choose SMS.",
      ],
      stepsNoAddress: [
        "Turn the proxy off: Settings → Wi-Fi → ⓘ → Configure Proxy → Off → Save.",
        "Open Authy and enter your phone number.",
        "Before you choose SMS, turn the proxy back on with the same Server and Port as before.",
        "Go back to Authy and choose SMS.",
      ],
    },
    wrongPassword: {
      title: "That password is not right.",
      body: (d: string) => `Nothing is lost. Use the password that unlocks Authy on your ${d}: the one Authy is asking for right now.`,
      kept: "What you typed is still in the box, so you can check it and try again.",
    },
    bitwardenServer: {
      title: "Bitwarden stopped part-way",
      body: "Everything done so far is saved. Run again to finish the rest. Nothing is added twice and no existing code is replaced.",
      detail: (message: string) => `Bitwarden said: ${message}`,
    },
    methodBroken: {
      title: "This method no longer works with Authy",
      body: "The certificate was trusted and working, but Authy now keeps refusing the connection. The likeliest reason is that Authy has changed and this app can no longer read its codes.",
      next: "Your codes are still safe in Authy. Clean up first, then move each account by hand.",
    },
  },

  device: {
    alt: {
      wifiOpen: (d: string) => `Drawing of ${d} Settings with the Wi-Fi row highlighted.`,
      wifiList: (d: string) => `Drawing of ${d} Settings, Wi-Fi. The ⓘ beside the connected network is highlighted.`,
      networkDetail: (d: string) => `Drawing of ${d} Wi-Fi network details. The Configure Proxy row is highlighted.`,
      proxyForm: (d: string, ip: string, port: number) =>
        `Drawing of ${d} Configure Proxy. Manual is selected, Server is ${ip}, Port is ${port}.`,
      proxySave: (d: string) => `Drawing of ${d} Configure Proxy with Save highlighted.`,
      proxyOff: (d: string) => `Drawing of ${d} Configure Proxy with Off selected and Save highlighted.`,
      downloadPage: (d: string) => `Drawing of Safari on ${d} showing the Download certificate button, highlighted.`,
      testPage: (d: string) => `Drawing of Safari on ${d} showing the Test link, highlighted.`,
      profileDownloaded: (d: string) => `Drawing of ${d} Settings with the Profile Downloaded row highlighted.`,
      installProfile: (d: string) => `Drawing of ${d} Install Profile with Install highlighted.`,
      trustSettings: (d: string) => `Drawing of ${d} Certificate Trust Settings with the switch for ${CERT_NAME} turned on.`,
      deviceManagement: (d: string) => `Drawing of ${d} VPN & Device Management showing the ${CERT_NAME} profile and Remove Profile.`,
      authyPrompt: (d: string) => `Drawing of Authy on ${d} asking for the backups password. Stop here.`,
      authyAccounts: (d: string) => `Drawing of Authy on ${d} with a list of accounts.`,
      authyBackups: (d: string) => `Drawing of Authy Settings, Accounts, on ${d} with Authenticator Backups switched on.`,
      authyPassword: (d: string) => `Drawing of Authy on ${d} asking for the backups password on a new device.`,
      authyDevices: (d: string) => `Drawing of Authy Settings, Devices, on ${d} with Allow Multi-device switched on.`,
      trashFile: "Drawing of a saved file being moved to the Trash.",
    },
    time: "9:41",
    settings: "Settings",
    yourName: "Your name",
    airplane: "Airplane Mode",
    wifi: "Wi-Fi",
    bluetooth: "Bluetooth",
    general: "General",
    accessibility: "Accessibility",
    privacy: "Privacy & Security",
    on: "On",
    off: "Off",
    homeNetwork: "Home Wi-Fi",
    myNetworks: "My networks",
    otherNetworks: "Other networks",
    neighbour: "Neighbour 5G",
    cafe: "Café Guest",
    forget: "Forget This Network",
    autoJoin: "Auto-Join",
    ipAddress: "IP Address",
    ipAddressValue: "192.168.4.57",
    automatic: "Automatic",
    httpProxy: "HTTP proxy",
    configureProxy: "Configure Proxy",
    manual: "Manual",
    server: "Server",
    port: "Port",
    authentication: "Authentication",
    save: "Save",
    profileDownloaded: "Profile Downloaded",
    installProfile: "Install Profile",
    cancel: "Cancel",
    install: "Install",
    signedBy: "Signed by",
    notSigned: "Not Signed",
    contains: "Contains",
    certificate: "Certificate",
    about: "About",
    trustTitle: "Certificate Trust Settings",
    trustGroup: "Enable full trust for root certificates",
    deviceManagement: "VPN & Device Management",
    vpn: "VPN",
    notConnected: "Not Connected",
    configProfile: "Configuration profile",
    removeProfile: "Remove Profile",
    safariHost: (ip: string, port: number) => `${ip}:${port}`,
    downloadCertificate: "Download certificate",
    test: "Test",
    authy: "Authy",
    authyAccounts: "Accounts",
    authyDevices: "Devices",
    authyBackupsTitle: "Backups password",
    authyBackupsBody1: "Enter your backups password",
    authyBackupsBody2: "to decrypt your accounts.",
    authyPasswordField: "Password",
    stopHere: "Stop here",
    authyBackupsToggle: "Authenticator Backups",
    authyMultiDevice: "Allow Multi-device",
    authyThisDevice: "This device",
    sampleAccounts: ["GitHub", "Google", "Amazon"],
    sampleCode: "••• •••",
    fileName: "authy-export",
    trash: "Trash",
  },
} as const;

export type DeviceLabel = (typeof en.deviceName)[keyof typeof en.deviceName];
