// All user-facing text lives here (English only). Components reference keys and never carry
// their own wording. Text that depends on a value is a small function.
//
// `d` is always the name of the person's device: "iPhone" or "iPad" once chosen, and
// "iPhone or iPad" before that.

const CERT_NAME = "authexodus (remove after use)";
const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const en = {
  appName: "authexodus",
  certName: CERT_NAME,

  deviceName: { iphone: "iPhone", ipad: "iPad", either: "iPhone or iPad" },

  common: {
    loading: "Starting…",
    havingTrouble: "Having trouble?",
    close: "Close",
    tryAgain: "Try again",
    back: "Back",
    done: "Done",
    previous: "Previous",
    next: "Next",
    pictureOf: (n: number, total: number) => `Picture ${n} of ${total}`,
    showPicture: "Show picture",
    hidePicture: "Hide picture",
    showPictureFor: (label: string) => `Show picture for: ${label}`,
    stopAndCleanUp: "Stop and clean up",
    loadFailed: "The app could not start.",
  },

  rail: {
    label: "Steps",
    steps: {
      welcome: "Safety check",
      connect: "Connect",
      certificate: "Certificate",
      authy: "Reinstall Authy",
      unlock: "Unlock",
      destination: "Move codes",
      verify: "Check codes",
      cleanup: "Clean up",
    },
    current: "current step",
    finished: "finished",
    version: (v: string) => `Version ${v}`,
  },

  welcome: {
    title: "Move your codes out of Authy",
    lede: "This app copies your two-step login codes from Authy into another authenticator app. It takes about 20 minutes, and everything happens on this computer and your own Wi-Fi.",
    planTitle: "What you will do",
    plan: [
      "Connect your iPhone or iPad to this computer for a few minutes.",
      "Delete Authy and install it again. This app catches the locked copy of your codes as Authy signs in.",
      "Unlock them here with your Authy backup password and move them to your new app.",
      "Put the iPhone or iPad back the way it was.",
    ],
    deviceQuestion: "Which device has Authy on it?",
    android: "Android phone",
    spare: "Safest: use a spare iPad or iPhone if you have one. Your everyday phone then keeps working the whole time.",
    androidTitle: "This app can't help with an Android phone",
    androidBody: "Getting codes out of Authy on Android needs changes to the phone that most people should not make. If you can borrow an iPhone or iPad, install Authy on it, sign in, and choose it above. Otherwise, move each account by hand.",
    checksTitle: "Check four things before you start",
    checksWhy: "You are going to delete Authy and install it again. Without these four, you could be locked out for 24 hours or lose codes.",
    checks: {
      device: {
        label: (d: string) => `Authy on this ${d} shows my codes`,
        where: "Open Authy and check that your accounts are listed.",
      },
      backups: {
        label: "Backups are turned on in Authy",
        where: "In Authy: Settings → Accounts → Authenticator Backups is switched on.",
      },
      password: {
        label: "I know my Authy backup password",
        where: "It unlocks your codes on a new device. It is not the passcode that unlocks the screen.",
      },
      multiDevice: {
        label: "Multi-device is turned on in Authy",
        where: "In Authy: Settings → Devices → Allow Multi-device is switched on.",
      },
    },
    start: "Start",
    blocked: "Choose your device and tick all four to start.",
    blockedChecks: (n: number) => `${plural(n, "check", "checks")} left to tick.`,
    footer: "authexodus is not affiliated with Twilio or Bitwarden. It exports your own data.",
  },

  connect: {
    title: (d: string) => `Connect your ${d} to this computer`,
    lede: (d: string) => `For the next few minutes your ${d} sends its internet traffic through this computer. Only Authy's traffic is read. Everything else passes straight through.`,
    starting: "Getting this computer ready…",
    startFailed: (d: string) => `This computer could not start listening for your ${d}.`,
    server: "Server",
    port: "Port",
    valuesLabel: (d: string) => `Type these on your ${d}`,
    addressLabel: "This computer's address",
    addressHint: (d: string) => `If your ${d} can't connect, try the other address.`,
    addressOption: (ip: string, label: string) => `${ip} (${label})`,
    steps: {
      wifi: { iphone: "Open Settings and tap Wi-Fi.", ipad: "Open Settings and tap Wi-Fi in the sidebar." },
      info: "Tap the blue ⓘ beside the network you are connected to.",
      configure: "Scroll down and tap Configure Proxy.",
      manual: (ip: string, port: number) => `Tap Manual. Type ${ip} for Server and ${port} for Port. Leave Authentication off.`,
      save: "Tap Save.",
    },
    firewall: "If your Mac asks whether to allow incoming connections, choose Allow.",
    waiting: (d: string) => `Waiting for your ${d} to connect. This screen moves on by itself.`,
  },

  certificate: {
    title: "Install the certificate",
    lede: "The certificate lets this computer read Authy's traffic while you do this. You will remove it at the end.",
    connected: (d: string) => `Your ${d} is connected.`,
    qrAlt: "QR code that opens the certificate download page",
    orType: "Or type this address into Safari:",
    steps: {
      scan: (d: string) => `Point the ${d}'s Camera at the code and open the link.`,
      download: "Tap Download certificate, then Allow.",
      profile: "Open Settings and tap Profile Downloaded near the top. If it is not there, go to General → VPN & Device Management.",
      install: "Tap Install, enter your passcode, and tap Install again.",
      trust: `The step people miss: go to Settings → General → About → Certificate Trust Settings and switch on ${CERT_NAME}.`,
      test: "Go back to the page from the first step and tap Test.",
    },
    waiting: "Waiting for the certificate to be trusted. This screen moves on by itself.",
  },

  authy: {
    title: "Delete Authy, then install it again",
    lede: "Authy has no sign-out, so this is the way to make it fetch your codes again. Your codes stay safe in Authy's backup.",
    trusted: "The certificate is trusted.",
    steps: {
      remove: (d: string) => `Delete the Authy app from your ${d}: touch and hold its icon, then Remove App → Delete App.`,
      install: "Install Authy again from the App Store and open it.",
      phone: "Enter your phone number and choose SMS to verify.",
      stop: "Stop when Authy asks for your backup password, and come back here.",
    },
    waiting: "Waiting for Authy to fetch your codes. This screen moves on by itself.",
  },

  unlock: {
    captured: (n: number) => `Captured ${plural(n, "account", "accounts")}`,
    title: "Unlock your codes",
    lede: "Type your Authy backup password. It is used only on this computer, exactly as you type it, and is never saved.",
    label: "Authy backup password",
    show: "Show password",
    hide: "Hide password",
    submit: "Unlock",
    working: "Unlocking…",
    alsoAuthy: (d: string) => `When this works, type the same password into Authy on your ${d} too. Authy then keeps working as a fallback.`,
    failed: "The codes could not be unlocked. Try again.",
  },

  destination: {
    title: "Where should your codes go?",
    lede: (n: number) => `${plural(n, "account is", "accounts are")} ready to move. Pick one way. You can come back and use another.`,
    none: "No accounts could be unlocked for moving.",
    options: {
      qr: { title: "Scan into any app", body: "One QR code per account. Works with every authenticator app." },
      bitwarden: { title: "Bitwarden, matched to your logins", body: "Adds each code to the login it belongs to. You review every match first." },
      google: { title: "Google Authenticator", body: "A few QR codes that each carry up to 10 accounts." },
      file: { title: "Save a file for another app", body: "1Password, 2FAS, Aegis, Proton Authenticator, Bitwarden, or plain text." },
    },
    usedTag: "used",
    continue: "Check the codes",
    cantMoveTitle: (n: number) => `${plural(n, "account", "accounts")} can't be moved`,
    cantMoveLede: "These stay in Authy until you set them up again yourself.",
    native: (name: string) => `${name} uses Authy's own 7-digit codes. Sign in to ${name}, open its security settings, and set up two-step login again with your new app.`,
    invalid: (name: string) => `${name} is not a usable authenticator key. Set up two-step login again in that account's security settings.`,
    backToOptions: "Back to the choices",

    qr: {
      title: "Scan each code with your new app",
      lede: "In your new app, choose to add an account by scanning a QR code. Scan this one, then go to the next.",
      position: (n: number, total: number) => `Account ${n} of ${total}`,
      alt: (name: string) => `QR code for ${name}`,
      loading: "Drawing the code…",
      warning: "Anyone who photographs these codes can copy your accounts. Keep the screen to yourself.",
    },
    google: {
      title: "Scan into Google Authenticator",
      lede: "In Google Authenticator, open the menu, then Transfer accounts → Import accounts, and scan each code.",
      position: (n: number, total: number) => `Code ${n} of ${total}`,
      alt: (n: number) => `Google Authenticator transfer code ${n}`,
    },
    file: {
      title: "Save a file for another app",
      lede: "Pick your app, save the file, then use that app's import option to open it.",
      warning: "The file holds the keys to your accounts with no lock on it. Import it, then delete it and empty the Trash.",
      save: (app: string) => `Save a file for ${app}`,
      saved: (path: string) => `Saved to ${path}`,
      cancelled: "Nothing was saved.",
      failed: "The file could not be saved. Try again.",
      apps: {
        onePassword: "1Password",
        twoFas: "2FAS",
        aegis: "Aegis",
        protonAuthenticator: "Proton Authenticator",
        bitwarden: "Bitwarden",
        plainText: "Plain text",
      },
    },
  },

  bitwarden: {
    introTitle: "Add your codes to Bitwarden",
    introBody: "To talk to Bitwarden, this app downloads Bitwarden's own command-line tool and checks that it is genuine. This is the only time the app uses the internet.",
    introNext: "After that you sign in, review every match, and only then is anything changed.",
    prepare: "Download and continue",
    preparing: "Downloading Bitwarden's tool and checking it…",
    prepareFailed: "The download did not work. Check this computer's internet connection and try again.",

    loginTitle: "Sign in to Bitwarden",
    loginLede: "Your master password goes to Bitwarden's tool on this computer and is then forgotten.",
    email: "Email address",
    password: "Master password",
    region: "Where is your Bitwarden account?",
    regions: { us: "bitwarden.com", eu: "bitwarden.eu", selfHosted: "My own server" },
    serverUrl: "Server address",
    serverUrlHint: "For example https://vault.example.com",
    twoFactor: "Two-step login code",
    needsTwoFactor: "Bitwarden needs your two-step login code. Enter it and sign in again.",
    badCredentials: "Bitwarden did not accept that email and master password. Check both and try again.",
    loginFailed: "Bitwarden could not be reached. Check this computer's internet connection and try again.",
    signIn: "Sign in",
    signingIn: "Signing in…",
    matching: "Reading your vault and matching accounts…",

    reviewTitle: "Review the matches",
    reviewLede: "Nothing has changed yet. A code that is already in Bitwarden is never replaced.",
    colAccount: "Authy account",
    colAction: "What to do in Bitwarden",
    question: "Which login is this?",
    choose: "Choose…",
    attach: (name: string, username: string | null) => (username ? `Add to ${name} (${username})` : `Add to ${name}`),
    attachHasCode: (name: string, username: string | null) =>
      `Already has a code, leave as it is: ${username ? `${name} (${username})` : name}`,
    createNew: "Create a new login in the “Authy import” folder",
    skip: "Skip this account",
    actionFor: (title: string) => `What to do with ${title}`,
    needChoice: (n: number) => `${plural(n, "account needs", "accounts need")} your choice first.`,
    apply: "Apply to Bitwarden",
    applying: "Adding codes to Bitwarden…",
    progressLabel: "Progress",

    reportTitle: "Bitwarden is updated",
    reportPartialTitle: "Bitwarden is partly updated",
    attached: (n: number) => `Added a code to ${plural(n, "login", "logins")}.`,
    created: (n: number) => `Created ${plural(n, "new login", "new logins")} in the “Authy import” folder.`,
    skipped: (n: number) => `Skipped ${plural(n, "account", "accounts")}.`,
    kept: (names: string[]) => `Left alone because a code was already there: ${names.join(", ")}.`,
    runAgain: "Run again",
  },

  verify: {
    title: "Check the codes match",
    lede: "Open your new app and compare a few accounts with the codes below. They should be identical. Codes change every 30 seconds.",
    listLabel: "Current codes",
    secondsLeft: (n: number) => `${n}s`,
    secondsLeftLabel: (n: number) => `${plural(n, "second", "seconds")} left`,
    loading: "Working out the codes…",
    mismatch: "A code doesn't match? Check that the date and time are set automatically where your new app is installed, then compare again.",
    forget: "After this step the app forgets your codes.",
    confirm: "They match. Clean up",
    another: "Move them to another app too",
  },

  cleanup: {
    title: "Put everything back",
    resumed: "The app was closed before clean-up finished last time. Finish these steps now.",
    working: "Stopping the connection and destroying the certificate key…",
    clean: "This computer is clean: the connection is stopped and the certificate key is destroyed.",
    failed: "This computer could not finish cleaning up.",
    deviceQuestion: "Which device did you use?",
    todo: (d: string) => `Now do these on your ${d}, and tick each one.`,
    items: {
      proxyOff: {
        label: "I turned the proxy off",
        how: "Settings → Wi-Fi → ⓘ beside your network → Configure Proxy → Off → Save.",
      },
      profileRemoved: {
        label: "I removed the certificate profile",
        how: `Settings → General → VPN & Device Management → ${CERT_NAME} → Remove Profile.`,
      },
      fileDeleted: {
        label: "I deleted the file I saved",
        how: "Import it into your new app first. Then delete it on this computer and empty the Trash.",
      },
    },
    keepAuthy: "Keep Authy installed for a week or two. If a code in your new app ever fails, Authy is still there.",
    remaining: (n: number) => `${plural(n, "item", "items")} left to tick.`,
    finish: "Finish",
  },

  done: {
    title: "All done",
    body: (d: string) => `Your ${d} and this computer are back to normal.`,
    keepAuthy: "Keep Authy installed for a week or two as a fallback.",
    close: "You can close this window.",
  },

  manual: {
    title: "Move an account by hand",
    steps: [
      "Sign in to the account on its website.",
      "Open its security settings and find two-step login. It may be called two-factor or 2FA.",
      "Choose to set up the authenticator app again. Use the code from Authy if it asks for one.",
      "Scan the new QR code with your new app and type in the code it shows.",
      "Repeat for each account. Keep Authy until every one is moved.",
    ],
  },

  failures: {
    sheetTitle: "Having trouble?",
    sheetLede: "These are the usual causes. Open the one that sounds right.",
    firewall: {
      title: "Your Mac may be blocking the connection",
      body: (d: string) => `When this app opened, your Mac may have asked whether authexodus can accept incoming network connections. If Deny was chosen, your ${d} can't reach this computer.`,
      steps: [
        "Open System Settings → Network → Firewall → Options.",
        "Find authexodus in the list and set it to Allow incoming connections.",
        "Or quit authexodus, open it again, and choose Allow when asked.",
      ],
    },
    wifi: {
      title: "Both devices must be on the same Wi-Fi",
      body: (d: string) => `Your ${d} and this computer have to be on the same Wi-Fi network.`,
      steps: (d: string, ip: string, port: number) => [
        `On the ${d}, check that Settings → Wi-Fi shows the same network name as this computer.`,
        "Guest, hotel and café networks often stop devices talking to each other. Use your home network, not its guest network.",
        `Check that Server and Port on the ${d} match exactly: ${ip} and ${port}.`,
      ],
      stepsNoAddress: (d: string) => [
        `On the ${d}, check that Settings → Wi-Fi shows the same network name as this computer.`,
        "Guest, hotel and café networks often stop devices talking to each other. Use your home network, not its guest network.",
      ],
    },
    vpn: {
      title: (d: string) => `Turn off VPN and iCloud Private Relay on the ${d}`,
      body: "Both send traffic around this computer, so nothing arrives here.",
      steps: [
        "Private Relay: Settings → your name → iCloud → Private Relay → switch off.",
        "VPN: Settings → VPN → switch off.",
        "Switch them back on when you have finished.",
      ],
    },
    trust: {
      title: "The certificate isn't trusted yet",
      body: (d: string) => `Installing the certificate is not enough. Your ${d} also needs trust switched on for it.`,
      steps: [
        "Open Settings → General → About.",
        "Scroll to the bottom and tap Certificate Trust Settings.",
        `Switch on ${CERT_NAME} and tap Continue.`,
        "Not in the list? The profile isn't installed yet. Go to Settings → General → VPN & Device Management and install it first.",
      ],
    },
    attestation: {
      title: "Authy showed an error",
      body: "If it mentions an “attestation token”, Authy is refusing to start while the proxy is on. Doing it in this order gets around it.",
      steps: (ip: string, port: number) => [
        "Turn the proxy off: Settings → Wi-Fi → ⓘ → Configure Proxy → Off → Save.",
        "Open Authy and enter your phone number.",
        `Before you choose SMS, turn the proxy back on: Manual, Server ${ip}, Port ${port}, Save.`,
        "Go back to Authy and choose SMS.",
      ],
      stepsNoAddress: [
        "Turn the proxy off: Settings → Wi-Fi → ⓘ → Configure Proxy → Off → Save.",
        "Open Authy and enter your phone number.",
        "Before you choose SMS, turn the proxy back on with the same Server and Port as before.",
        "Go back to Authy and choose SMS.",
      ],
    },
    wrongPassword: {
      title: "That password is not right.",
      body: (d: string) => `Nothing is lost. Use the password that unlocks Authy on your ${d}: the one Authy is asking for right now.`,
      kept: "What you typed is still in the box, so you can check it and try again.",
    },
    bitwardenServer: {
      title: "Bitwarden stopped part-way",
      body: "Everything done so far is saved. Run again to finish the rest. Nothing is added twice and no existing code is replaced.",
      detail: (message: string) => `Bitwarden said: ${message}`,
    },
    methodBroken: {
      title: "This method no longer works with Authy",
      body: "The certificate is trusted, but Authy still refuses the connection. That means Authy has changed, and this app can no longer read its codes. It is not something you did.",
      next: "Your codes are still safe in Authy. Clean up first, then move each account by hand.",
    },
  },

  device: {
    alt: {
      wifiOpen: (d: string) => `Drawing of ${d} Settings with the Wi-Fi row highlighted.`,
      wifiList: (d: string) => `Drawing of ${d} Settings, Wi-Fi. The ⓘ beside the connected network is highlighted.`,
      networkDetail: (d: string) => `Drawing of ${d} Wi-Fi network details. The Configure Proxy row is highlighted.`,
      proxyForm: (d: string, ip: string, port: number) =>
        `Drawing of ${d} Configure Proxy. Manual is selected, Server is ${ip}, Port is ${port}.`,
      proxySave: (d: string) => `Drawing of ${d} Configure Proxy with Save highlighted.`,
      proxyOff: (d: string) => `Drawing of ${d} Configure Proxy with Off selected and Save highlighted.`,
      downloadPage: (d: string) => `Drawing of Safari on ${d} showing the Download certificate button, highlighted.`,
      testPage: (d: string) => `Drawing of Safari on ${d} showing the Test link, highlighted.`,
      profileDownloaded: (d: string) => `Drawing of ${d} Settings with the Profile Downloaded row highlighted.`,
      installProfile: (d: string) => `Drawing of ${d} Install Profile with Install highlighted.`,
      trustSettings: (d: string) => `Drawing of ${d} Certificate Trust Settings with the switch for ${CERT_NAME} turned on.`,
      deviceManagement: (d: string) => `Drawing of ${d} VPN & Device Management showing the ${CERT_NAME} profile and Remove Profile.`,
      authyPrompt: (d: string) => `Drawing of Authy on ${d} asking for the backups password. Stop here.`,
      authyAccounts: (d: string) => `Drawing of Authy on ${d} with a list of accounts.`,
      authyBackups: (d: string) => `Drawing of Authy Settings, Accounts, on ${d} with Authenticator Backups switched on.`,
      authyPassword: (d: string) => `Drawing of Authy on ${d} asking for the backups password on a new device.`,
      authyDevices: (d: string) => `Drawing of Authy Settings, Devices, on ${d} with Allow Multi-device switched on.`,
      trashFile: "Drawing of a saved file being moved to the Trash.",
    },
    time: "9:41",
    settings: "Settings",
    search: "Search",
    appleAccount: "Apple Account, iCloud and more",
    yourName: "Your name",
    airplane: "Airplane Mode",
    wifi: "Wi-Fi",
    bluetooth: "Bluetooth",
    cellular: "Cellular",
    general: "General",
    accessibility: "Accessibility",
    privacy: "Privacy & Security",
    on: "On",
    off: "Off",
    homeNetwork: "Home Wi-Fi",
    myNetworks: "My networks",
    otherNetworks: "Other networks",
    neighbour: "Neighbour 5G",
    cafe: "Café Guest",
    forget: "Forget This Network",
    autoJoin: "Auto-Join",
    ipAddress: "IP Address",
    ipAddressValue: "192.168.4.57",
    configureDns: "Configure DNS",
    automatic: "Automatic",
    httpProxy: "HTTP proxy",
    configureProxy: "Configure Proxy",
    manual: "Manual",
    server: "Server",
    port: "Port",
    authentication: "Authentication",
    save: "Save",
    profileDownloaded: "Profile Downloaded",
    installProfile: "Install Profile",
    cancel: "Cancel",
    install: "Install",
    signedBy: "Signed by",
    notSigned: "Not Signed",
    contains: "Contains",
    certificate: "Certificate",
    about: "About",
    trustTitle: "Certificate Trust Settings",
    trustGroup: "Enable full trust for root certificates",
    deviceManagement: "VPN & Device Management",
    vpn: "VPN",
    notConnected: "Not Connected",
    configProfile: "Configuration profile",
    removeProfile: "Remove Profile",
    safariHost: (ip: string, port: number) => `${ip}:${port}`,
    downloadCertificate: "Download certificate",
    test: "Test",
    authy: "Authy",
    authyAccounts: "Accounts",
    authyDevices: "Devices",
    authyBackupsTitle: "Backups password",
    authyBackupsBody1: "Enter your backups password",
    authyBackupsBody2: "to decrypt your accounts.",
    authyPasswordField: "Password",
    stopHere: "Stop here",
    authyBackupsToggle: "Authenticator Backups",
    authyMultiDevice: "Allow Multi-device",
    authyThisDevice: "This device",
    sampleAccounts: ["GitHub", "Google", "Amazon"],
    sampleCode: "••• •••",
    fileName: "authy-export",
    trash: "Trash",
  },

  dev: {
    title: "Pretend phone",
    note: (password: string) => `Not the real app. Backup password: ${password}`,
    deviceConnected: "Device connects",
    trustWorking: "Trust works",
    tlsRejected: "Certificate refused",
    authyError: "Authy error",
    backupCaptured: "Backup captured",
    bwFail: "Next apply fails",
    bwFailMessage: "503 Service Unavailable",
    hide: "Hide",
    show: "Pretend phone",
  },
} as const;

export type DeviceLabel = (typeof en.deviceName)[keyof typeof en.deviceName];
